version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Server/Dockerfile
    container_name: legalai-backend
    ports:
      - "8000:8000"
    environment:
      API_SECRET_KEY: "SuperSecureSecretKey123"
    volumes:
      - ./Data:/app/Data
      - ./Output:/app/Output
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: legalai-frontend
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: "http://backend:8000"
      API_SECRET_KEY: "SuperSecureSecretKey123"
    depends_on:
      - backend
    restart: always
